version: '3'

networks:
  net:
    driver: bridge

volumes:
  data-vol:
    driver: local
  app-vol:
    driver: local

services:
  dbase:
    image: postgres:15.3-alpine
    container_name: grocery-shop-db
    networks:
      - net
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
#    ports:
#      - '5433:5432'
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
      - data-vol:/var/lib/postgresql/data
  app:
    build:
      context: .
    image: grocery-shop-app:1.0
    container_name: grocery-shop-app
    networks:
      - net
    ports:
      - "8080:8080"
    depends_on:
      - dbase
    env_file:
      - .env
    volumes:
      - app-vol:/app