spring:
  config.import: optional:file:.env[.properties]
  jpa:
    properties:
      hibernate.show_sql: false

  liquibase:
    default-schema: ${POSTGRES_SCHEMA}

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

logging:
  file:
    path: ../app/logs/grocery
    name: ${logging.file.path}/grocery.log

app:
  image:
    product: ../app/images/products
    user: ../app/images/users
  init:
    admin:
      name: ${INIT_USERNAME}
      login: ${INIT_LOGIN}
      password: ${INIT_PASSWORD}

